import type { Metadata } from "next";
import "./globals.css";
import { beVNPro } from "@/utils";
import Sidebar from "@/components/layouts/Sidebar";


export const metadata: Metadata = {
  title: "E-Learning App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={beVNPro.className}>
        <div className="wrapper grid grid-cols-[300px_minmax(0,1fr)]">
          <Sidebar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
